### ISSUE TITLE
Read values from plant domain

### ISSUE THREAD

**Issue by k1rd3rf** [RodBr/miflora-card#13]
It would be nice to specify one entity instead of each and every entity, since HA support the plant domain.

```
plant:
  ficus:
    sensors:
      moisture: sensor.plant_ficus_moisture
      conductivity: sensor.plant_ficus_conductivity
      brightness: sensor.plant_ficus_brightness
      temperature: sensor.plant_ficus_temperature
      battery: sensor.plant_ficus_battery
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 2500
    max_brightness: 35000
    min_temperature: 8
    max_temperature: 32
    min_battery: 15
```

lovelace:
```
- type: custom:miflora-card
  title: 'Ficus microcarpa'
  image: images/ficus_microcarpa.jpg
  plant: plant.ficus
```
