### ISSUE TITLE
Uncaught TypeError: config.entities[i].split is not a function

### ISSUE THREAD

**Issue by cftechwiz** [RodBr/miflora-card#20]
2021-09-18 12:54:44 ERROR (MainThread) [frontend.js.latest.202108300] http://hassio.local:8123/hacsfiles/miflora-card/miflora-card.js?hacstag=197715418010:58:46 Uncaught TypeError: config.entities[i].split is not a function
2021-09-18 12:54:44 ERROR (MainThread) [aiohttp.web] Forbidden
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/http/static.py", line 30, in _handle
    raise HTTPForbidden()
aiohttp.web_exceptions.HTTPForbidden: Forbidden

**Comment by OscarHanzely** [comment]
I am getting the same error, in addition to the card does not show up and is breaking the dashboard that is attached to. This card is no longer compatible with ha core version 2022.1

**Comment by WalterDSU** [comment]
It is breaking my dashboard. anyone can help to fix it for newer version2022.

**Comment by fontanon** [comment]
I'm getting this issue too .. here's my card.

```yaml
type: custom:miflora-card
entities:
  - entity: sensor.dragino_moisture_terraza1_water_soil
    type: moisture
  - entity: sensor.dragino_moisture_terraza1_temp_soil
    type: temperature
  - entity: sensor.dragino_moisture_terraza1_conduct_soil
    type: conductivity
    name: Fertility
  - entity: sensor.dragino_moisture_terraza1_bat
    type: battery
title: Calathea Zebrina
image: images/calathea-zebrina.jpg
min_moisture: 15
max_moisture: 60
min_conductivity: 350
min_temperature: 12
```

I'm using version `0.1.0` as downloaded from HACS. 

**IMPORTANT NOTE**: Using HACS to install, if you mark `Allow Beta Downloads` and select `master` branch ... it worked for me!
